# This file was generated by GoReleaser. DO NOT EDIT.
cask "mitosis" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c69b9402b4077d89eb649cb9d3c89845dae2a4666102f17d4cfd8bb6c4d73927"
      url "https://github.com/butterball04/mitosis/releases/download/v#{version}/mitosis-darwin-amd64.tar.gz",
        verified: "github.com/butterball04/mitosis/"
    end
    on_arm do
      sha256 "873b9c255446c2fa7b2d210d74aea018a20594a93f3fc61a2eb965a9e1ceec92"
      url "https://github.com/butterball04/mitosis/releases/download/v#{version}/mitosis-darwin-arm64.tar.gz",
        verified: "github.com/butterball04/mitosis/"
    end
  end

  on_linux do
    on_intel do
      sha256 "50829477f1d1e3ac5eb51ae1fff2f7fd30b88db75a7af815f342b119bae9a355"
      url "https://github.com/butterball04/mitosis/releases/download/v#{version}/mitosis-linux-amd64.tar.gz",
        verified: "github.com/butterball04/mitosis/"
    end
    on_arm do
      sha256 "f97fee3077874fce915270cfd85c9444a82fcb40027a031b7df8ea1baf1d3ae2"
      url "https://github.com/butterball04/mitosis/releases/download/v#{version}/mitosis-linux-arm64.tar.gz",
        verified: "github.com/butterball04/mitosis/"
    end
  end

  name "mitosis"
  desc "Instant, isolated database branches for development"
  homepage "https://github.com/butterball04/mitosis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mitosis"

  # No zap stanza required

end
