# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mitosis < Formula
  desc "Instant, isolated database branches for development"
  homepage "https://github.com/butterball04/mitosis"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://mitosis-releases.s3.ap-northeast-1.amazonaws.com/v0.1.0/mitosis-darwin-amd64.tar.gz"
      sha256 "25a97f6544b4ac43ab93f9ff50ed4f8010109f8f9e0f9e759d697cb161335f68"

      define_method(:install) do
        bin.install "mitosis"
      end
    end
    if Hardware::CPU.arm?
      url "https://mitosis-releases.s3.ap-northeast-1.amazonaws.com/v0.1.0/mitosis-darwin-arm64.tar.gz"
      sha256 "619f149eb80c7f2f6463ceef7b5ad9d8faeef4d8416307032c7808a0f832c833"

      define_method(:install) do
        bin.install "mitosis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://mitosis-releases.s3.ap-northeast-1.amazonaws.com/v0.1.0/mitosis-linux-amd64.tar.gz"
      sha256 "d1ccd0ab9d603fc249cd4c524638a91ccfb774e8f0b9be7bdbb3ac93126de634"
      define_method(:install) do
        bin.install "mitosis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://mitosis-releases.s3.ap-northeast-1.amazonaws.com/v0.1.0/mitosis-linux-arm64.tar.gz"
      sha256 "f8e48f6ee6c80af59c0a59da1cbceaabaee0769db43f5b8e537e9db8ab24bd03"
      define_method(:install) do
        bin.install "mitosis"
      end
    end
  end

  test do
    system "#{bin}/mitosis", "version"
  end
end
